### PR TITLE
Adding these URLs

### PR DESCRIPTION
**Pull request by whoacowboy**
Added URLs and compiled
## Description

www.cuztzjxdj.us  
www.eoraphogcys.fr  
www.gimcdvh.ru  
www.gnvuytupzwx.co.uk  
www.hffilinjpp.co.uk  
www.idqhh.br
www.iumspy.org  
www.jxfzwuyuafom.au 
www.lvuaqenztvnq.info  
www.pybbeg.it  
www.rgkzr.info  
www.rqojbn.br  
www.trgsjoewqx.fr  
www.uyopnt.org  
www.vqpemhypeg.us  
www.xuufvtsekgtm.info  
www.zzbtkvcc.info

### CODE REVIEW

**Comment by Stevie-Ray** [comment]
can't find anything about these URL's where did you find them?

**Comment by Stevie-Ray** [comment]
@whoacowboy WHY DID YOU COMMIT THIS BULLSHIT?

**Comment by whoacowboy** [comment]
Hi @Stevie-Ray, be cool.
These came up on our site, just trying to help.
Feel free not to merge.

screen shot 2016-04-09 at 3 12 58 pm

**Comment by Stevie-Ray** [comment]
@whoacowboy next time please Google the URL's you commit: There isn't a single result about all the urls you've committed. Maybe somebody is trying to manipulate your personal Google Analytics data. They look really strange to me, like keyboard mashing ;-)

**Comment by whoacowboy** [comment]
@Stevie-Ray they do look odd. I was just going off of what I saw on my analytics. I will run them through google next time. Didn't mean to cause you strife. Your repo has rally helped me out. I can't help but think why would anybody just try to manipulate google analytics? Maybe they are looking for some sort of weakness.

**Pull request merged**
