### PR TITLE
Added "adf.ly"

### PR DESCRIPTION
**Pull request by Hendriksie**
Last 2 days I received a lot of referral spam from "adf.ly"

### CODE REVIEW

**Comment by Stevie-Ray** [comment]
adf.ly offers a "URL shortener" service with a payment scheme, are you sure this is 'ghost' spam traffic?

**Comment by Hendriksie** [comment]
I'm not 100% sure, but in a timespan of 5 seconds, I got over 30 hits

**Comment by thiagotalma** [comment]
@Stevie-Ray this is not referral spam.

**Comment by Stevie-Ray** [comment]
@thiagotalma thanks, that's why I think it is a bad idea to block this website in this file. 
For now, I will keep an eye on my Google Analytics.
But still, thanks (bedankt!) @Hendriksie for reporting and doing the effort to create a pull request!!

**Comment by borisdifiore** [comment]
Hi,
it started to hits also my e-commerce site. I don't know how adf.ly exactly works, I mean the services it provides and referred by Stevie, but for sure I didn't buy it, so why it is coming to my site? 
I hope this can help the discussion.
Thanks all

**Comment by Hendriksie** [comment]
Hi, sorry for the doubtful result, but as far as statistics go in Google Analytics, there is no difference as lets say 'get-your-social-buttons.info'.
Analytics Image
If I look at the homepage of adf.ly, I see that hey are selling visitors for links, but I may misunderstand the purpose.

**Comment by jusurb** [comment]
yes, looks like adf.ly is a service, which provides a way to earn money from clicking on the url. A user creates a link, to a site, and shares it, when someone clicks on it he/she has to see and ad for about 10 s. then they are redirected to the link intended.
So someone could by earning money by sharing your site links. I too got report from my client in e-commerce that this was a referrer spam, but now i think it's most likely not.

i'll modify my pull request accordingly.

**Comment by Stevie-Ray** [comment]
still it's a little wierd, this is the second time they got reported.

**Comment by Stevie-Ray** [comment]
#47 third time it got reported, i wil merge it #46 thanks for your time @gamesh @Hendriksie @borisdifiore @mthjn and @thiagotalma!! Guys let me know your thoughts about this type of ghost spam. The spammers used adf.ly to make money: If someone visited that URL the spammer will get some commission from the ad (but there account already got suspended). So should I keep it in there or not?

**Comment by borisdifiore** [comment]
"The spammers used adf.ly to make money: If someone visited that URL the spammer will get some commission from the ad (but there account already got suspended). So should I keep it in there or not?"
@Stevie-Ray I will block adf.ly because I didn't buy its services. I also agree with you spammers can buy plans to make money from the ad. On the other hand some user can choose to buy adf.ly services and he can be interested to track adf. So, I don't know if it is possible by a technical point of view, you can add an option allowing the users to include or not the adf in your block list.

**Pull request closed without merging**
