### PR TITLE
Files generator

### PR DESCRIPTION
**Pull request by thiagotalma**
Automating the maintenance of files using Autohotkey.
Only the "domains.txt" file must be changed. Then run the generator.

Thus we facilitate the change and ensure that the changes will always have the same pattern.

### CODE REVIEW

**Comment by Stevie-Ray** [comment]
damn that looks good, thanks for your contribution!

**Comment by Stevie-Ray** [comment]
The only downside is that it's windows only, right? :-1: 

@chauncey-garrett made a shell script: 
https://github.com/chauncey-garrett/referral-spam-blacklist/blob/master/src/generate.sh

Maybe we can create something like this for Unix/Mac users.

**Comment by thiagotalma** [comment]
@Stevie-Ray how OS you use?
This generator is for you.
Collaborators alter ONLY the domains.txt file.
Then you run the generator and commit the files.

**Comment by Stevie-Ray** [comment]
I use Mac OSX, so i can **not** use your generator! It looks good though.

**Comment by thiagotalma** [comment]
@Stevie-Ray try this: http://www.autohotkey.com/board/topic/79804-ahk-version-for-the-mac/

**Comment by Stevie-Ray** [comment]
I also read an article about [Keyboard Maestro](http://www.keyboardmaestro.com/main/), will take a look at these programs soon..

**Pull request merged**
